name: Security Scan

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  gitleaks:
    uses: redacted-org/.github/.github/workflows/gitleaks.yml@main
    permissions:
      contents: read
      security-events: write
      actions: read

  trivy:
    uses: redacted-org/.github/.github/workflows/trivy.yml@main
    permissions:
      contents: read
      security-events: write
      actions: read

  opengrep:
    uses: redacted-org/.github/.github/workflows/opengrep.yml@main
    permissions:
      contents: read
      security-events: write
      actions: read
